### ISSUE TITLE
Access values with path

### ISSUE THREAD

**Issue by legrandp** [jjhelmus/pyfive#15]
One thing that is not yet possible and that would help a lot. For example, with version 0.2.0:
Using Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2

> > > import h5py
> > > import pyfive
> > > 
> > > f5 = h5py.File('tests/latest.hdf5')
> > > f5["group1/subgroup1/dataset3"].value
> > > array([ 0.,  1.,  2.,  3.], dtype=float32)
> > > ffive = pyfive.File('tests/latest.hdf5')
> > > ffive["group1/subgroup1/dataset3"].value
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "pyfive/high_level.py", line 48, in **getitem**
> > >     raise KeyError('%s not found in group' % (y))
> > > KeyError: 'group1/subgroup1/dataset3 not found in group'

**Comment by jjhelmus** [comment]
Agreed.  This should be possible by changing the logic in `Group.__getitem__` method.  Hope to have some time to look at this later this week.

**Comment by jjhelmus** [comment]
Labelling `bug` as this feature works in h5py.

**Comment by legrandp** [comment]
Dear Jonathan,
Thanks for the progress on this feature. The access by path works but, unfortunately, the value attribute cannot be read:

>>> import pyfive
>>> pyfive.__version__
'0.4.0.dev'
>>> ffive = pyfive.File('tests/latest.hdf5')
>>> ffive["group1/subgroup1/dataset3"].value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Dataset' object has no attribute 'value'

Is there another way to access "value" attributes ?

**Comment by jjhelmus** [comment]
The .value attribute is deprecated in h5py, see h5py/h5py#209.  The preferred syntax to access the contents of the data would be `ffive["group1/subgroup1/dataset3'][()]`.  This will work in both pyfive and h5py.  

I'll add a .value attribute to the Dataset class for compatibility.

**Comment by legrandp** [comment]
Great! Thanks a lot for clarifying this and for the compatibility commit.
