### ISSUE TITLE
Superblock V3 error

### ISSUE THREAD

**Issue by RossSmyth** [jjhelmus/pyfive#45]
Hello!

I attempted to use this library to open an HDF5 file I have, and it errored when opening it saying:

> NotImplementedError: unsupported superblock version: 3

But looking at the checks [here](https://github.com/jjhelmus/pyfive/blob/master/pyfive/misc_low_level.py#L25) shouldn't version 3 be supported? Also I can confirm that I am using pyfive 0.3.0.

**Comment by kalvdans** [comment]
Seems the support for version 3 was [added](https://github.com/jjhelmus/pyfive/commit/bf585d5c442a38a1f21d2363499f5ac63e914d3d) after the 0.3.0 was [released](https://github.com/jjhelmus/pyfive/releases/tag/v0.3.0).

**Comment by RossSmyth** [comment]
Ah good point, I didn't look at how recent 0.3.0 was.
